name: flutter_plate_keyboard
description: flutter_plate_keyboard.
version: 0.0.1
homepage: https://github.com/zhazhazsy/flutter_plate_keyboard

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_smart_dialog: 4.5.3+8   # dialog
flutter:
